#! /bin/sh

# Start SXHKD
pgrep -x sxhkd > /dev/null || sxhkd &

# Bspwm Config
bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#83c092"

# AutoStart
run() {
  if ! pidof -q "$1"; then
    "$@" &
  fi
}

run picom
run polybar

feh --bg-fill ~/dotfiles/wallpaper.jpg
