[color]
bg = #181818
fg = #e0d8c8
innerbox = #1F1F1F
orangered = #E69875
blue = #458588
green = #83c092
yellow = #E3E094
mustard = #b5ac9c

[global/wm]
include-file = modules.ini
margin-bottom = 0
margin-top = 0

[bar/bar]
; Text
font-0 = "IntoneMono Nerd Font:style=Bold:size=8.7;2"
; Small text
font-1 = "IntoneMono Nerd Font:style=Bold:size=7.9;2"
; Small icon
font-2 = "IntoneMono Nerd Font:style=Bold:size=8.2;3"
; Icon padding
font-3 = "IntoneMono Nerd Font:style=Bold:size=8.7;3"
; Asian
font-4 = "NotoSansJp:style=Bold:size=8;2"
; Glyphs
font-5 = "MesloLGS NF:style=Regular:pixelsize=17;4"

monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false
fixed-center = true

bottom = false

width = 100%
height = 20

background = ${color.bg}
foreground = ${color.fg}

border-size = 8px
border-color = ${color.bg}

padding = 1

module-margin-left = 0
module-margin-right = 0

modules-left = bi bspwm bd sep bi memory bd sep bi cpu bd
modules-center = playing
modules-right = bi pulseaudio bd sep bi date bd

separator =
dim-value = 1.0

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll =

[settings]
screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
